# Generated by Django 4.1.4 on 2022-12-08 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_termos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Termos',
        ),
    ]
